### ISSUE TITLE
Open or close the Edit field when clicking on the gray zone

### ISSUE THREAD

**Issue by Meier-Link** [spiral-project/formbuilder#18]
There is a problem with the padding. If we click on it, the edit zone is not opened/close.

**Comment by almet** [comment]
Thanks for reporting this.

I believe we have different problems here:
- the zone to select to open the editor isn't large enough;
- the editor doesn't close when we click an another zone (and it should be the case).

To fix this, I believe we should move away from using the react-bootstrap component and instead use our own mechanism where we can define ourselves explicitely how the click behaviours should be.

I'm actually more and more enclined to change the way the editor is shown. Having this little pop-over seemed to be a good idea, but if we could directly edit the field themselves, that would probably be easier to use.

@Meier-Link are you willing to work on this or was it just to report the issue ?
