### ISSUE TITLE
remove the req to require.js, we don't need this

### ISSUE THREAD

**Issue by almet** [spiral-project/formbuilder#7]
I think that would be far better if we don't have a requirement to require.js. It will simplify the dev process and let us debug stuff more easily.

**Comment by Natim** [comment]
Yes I agree, we could also use Grunt to manage dependencies.

**Comment by almet** [comment]
Grunt is not for dependencies, maybe you're thinking about bower?

**Comment by Natim** [comment]
No brunch sorry.

**Comment by almet** [comment]
http://brunch.io/ ?
