### ISSUE TITLE
UI inspiration for permissions management

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/formbuilder#8]
Taken from bitbucket : 

![screen shot 2014-09-07 at 16 35 15](https://cloud.githubusercontent.com/assets/546692/4757114/f87aee6c-5ad2-11e4-8bbd-d7184a93a479.png)

**Comment by Natim** [comment]
We don't plan to add permission management to the form builder so far.

**Comment by almet** [comment]
This would mean we have a notion of users in daybed, but that's not the case yet :)

**Comment by almet** [comment]
(and I don't believe we want that. Have a look at [how we're dealing with sharing](https://spiral-project.github.io/formbuilder/#/edit/ecd3caf784fb48d189d43de115e84fc2/2ad8361f9447299135c2dc849711962d6a1b6761ee1298db09acc2e5ff64fe8f) here when you click on the button on the top.

**Comment by almet** [comment]
I'm closing this for now. I think that's a good idea but not directly for the form builder. Feel free to reopen if you disagree.
